Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider "Hyper-V" do |hv|
    hv.vmname = "Ubuntu2004"
    hv.cpus = "2"
    hv.memory = "2048"
    hv.enable_enhanced_session_mode = true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end
end
